#Eureka-Server Config
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  instance:
    hostname: localhost
    
#Server Config
server:
  port: 8761
  
#Application Name
spring:
  application:
    name: GAMV_WIND-EUREKA-SERVER

